import {
  // MdAutocompleteModule,
  MdButtonModule,
  MdButtonToggleModule,
  MdCardModule,
  MdCheckboxModule,
  // MdChipsModule,
  // MdDatepickerModule,
  MdDialogModule,
  // MdGridListModule,
  MdIconModule,
  MdInputModule,
  MdListModule,
  // MdMenuModule,
  MdCoreModule,
  // MdProgressBarModule,
  // MdProgressSpinnerModule,
  // MdRadioModule,
  // MdRippleModule,
  MdSelectModule,
  MdSidenavModule,
  MdSlideToggleModule,
  // MdSliderModule,
  MdSnackBarModule,
  // MdTabsModule,
  MdToolbarModule,
  MdTooltipModule,
  // MdNativeDateModule,
} from '@angular/material';
export const MATERIAL_MODULES = [
  // MdAutocompleteModule,
  MdButtonModule,
  MdButtonToggleModule,
  MdCardModule,
  MdCheckboxModule,
  // MdChipsModule,
  // MdDatepickerModule,
  MdDialogModule,
  // MdGridListModule,
  MdIconModule,
  MdInputModule,
  MdListModule,
  // MdMenuModule,
  MdCoreModule,
  // MdProgressBarModule,
  // MdProgressSpinnerModule,
  // MdRadioModule,
  // MdRippleModule,
  MdSelectModule,
  MdSidenavModule,
  MdSlideToggleModule,
  // MdSliderModule,
  MdSnackBarModule,
  // MdTabsModule,
  MdToolbarModule,
  MdTooltipModule,
  // MdNativeDateModule,
];
