import {
  // MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  // MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatFormFieldModule,
  // MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  // MatMenuModule,
  // MatCoreModule,
  MatProgressBarModule,
  // MatProgressSpinnerModule,
  // MatRadioModule,
  // MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  // MatSliderModule,
  MatSnackBarModule,
  // MatTabsModule,
  MatTableModule,
  MatToolbarModule,
  MatTooltipModule,
  MatNativeDateModule
} from '@angular/material';
import { CdkTableModule } from '@angular/cdk/table';
export const MATERIAL_MODULES = [
  CdkTableModule,
  // MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  // MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatFormFieldModule,
  // MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  // MatMenuModule,
  // MatCoreModule,
  MatProgressBarModule,
  // MatProgressSpinnerModule,
  // MatRadioModule,
  // MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  // MatSliderModule,
  MatSnackBarModule,
  MatTableModule,
  // MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatNativeDateModule
];
